version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - chainlit
      - frontend

  chainlit:
    build:
      context: ./rag-chatbot
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
