name: deploy the server to azure web apps

on:
  push:
    branches: main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout github
        uses: actions/checkout@v3

      - name: setup nodejs version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: install dependencies
        run: |
          cd server
          npm ci --production

      - name: setup python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install Python dependencies
        run: |
          cd server
          pip install uv
          uv venv
          source .venv/bin/activate

      - name: Clean up unnecessary files
        run: |
          cd server
          rm -rf node_modules

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy to azure app services
        uses: azure/webapps-deploy@v2
        with:
          app-name: "ayurvision"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: "server"
