name: deploy the server to azure web apps

on:
  push:
    branches: main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout github
        uses: actions/checkout@v3

      - name: setup nodejs version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: install dependencies
        run: |
          cd server
          npm install

      - name: deploy to azure app services
        uses: azure/webapps-deploy@v2
        with:
          app-name: "ayurvision"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: "server"
